export function adjustHue(...args: any[]): any;
export function animation(...args: any[]): any;
export function backgroundImages(...args: any[]): any;
export function backgrounds(...args: any[]): any;
export function between(fromSize: any, toSize: any, minScreen: any, maxScreen: any): any;
export function border(sideKeyword: any, ...args: any[]): any;
export function borderColor(...args: any[]): any;
export function borderRadius(side: any, radius: any): any;
export function borderStyle(...args: any[]): any;
export function borderWidth(...args: any[]): any;
export function buttons(...args: any[]): any;
export function clearFix(parent: any): any;
export function complement(color: any): any;
export function cover(offset: any): any;
export function darken(...args: any[]): any;
export function desaturate(...args: any[]): any;
export function directionalProperty(property: any, ...args: any[]): any;
export function ellipsis(width: any): any;
export function em(pxval: any, base: any): any;
export function fluidRange(cssProp: any, minScreen: any, maxScreen: any): any;
export function fontFace(_ref: any): any;
export function getLuminance(color: any): any;
export function getValueAndUnit(value: any): any;
export function grayscale(color: any): any;
export function hiDPI(ratio: any): any;
export function hideText(): any;
export function hideVisually(): any;
export function hsl(value: any, saturation: any, lightness: any): any;
export function hslToColorString(color: any): any;
export function hsla(value: any, saturation: any, lightness: any, alpha: any): any;
export function invert(color: any): any;
export function lighten(...args: any[]): any;
export function linearGradient(_ref: any): any;
export function margin(...args: any[]): any;
export function math(formula: any, additionalSymbols: any): any;
export function mix(...args: any[]): any;
export function modularScale(steps: any, base: any, ratio: any): any;
export function normalize(): any;
export function opacify(...args: any[]): any;
export function padding(...args: any[]): any;
export function parseToHsl(color: any): any;
export function parseToRgb(color: any): any;
export function position(positionKeyword: any, ...args: any[]): any;
export function radialGradient(_ref: any): any;
export function readableColor(color: any, lightReturnColor: any, darkReturnColor: any): any;
export function rem(pxval: any, base: any): any;
export function retinaImage(filename: any, backgroundSize: any, extension: any, retinaFilename: any, retinaSuffix: any): any;
export function rgb(value: any, green: any, blue: any): any;
export function rgbToColorString(color: any): any;
export function rgba(firstValue: any, secondValue: any, thirdValue: any, fourthValue: any): any;
export function saturate(...args: any[]): any;
export function setHue(...args: any[]): any;
export function setLightness(...args: any[]): any;
export function setSaturation(...args: any[]): any;
export function shade(...args: any[]): any;
export function size(height: any, width: any): any;
export function stripUnit(value: any, unitReturn: any): any;
export function textInputs(...args: any[]): any;
export function timingFunctions(timingFunction: any): any;
export function tint(...args: any[]): any;
export function toColorString(color: any): any;
export function transitions(...args: any[]): any;
export function transparentize(...args: any[]): any;
export function triangle(_ref: any): any;
export function wordWrap(wrap: any): any;
